import { mockJsonResponse } from "@/test/testUtils";

const FIXTURES: Record<string, unknown> = {
  "/profile": {
    full_name: "Daniele Mario Areddu",
    roles: ["Backend & AI Developer"],
    location: "Velletri, Italy",
    base_country: "Italy",
    availability: "Available",
    tagline: "Building intelligent systems. Sharing what I learn around the world.",
    positioning_statement: "Backend & AI Developer.",
    brand_label: "Backend × AI × Communities",
    public_email: "danielemario@areddu.it",
    github_url: null,
    linkedin_url: null,
    sessionize_url: null,
    talks_count_label: "30+",
    speaking_years_label: "2",
    speaking_regions_label: "Europe, North America, Central Asia",
  },
  "/biography": {
    micro: "Backend & AI Developer.",
    short: "Short bio.",
    medium: "Medium bio.",
    long: "Long bio paragraph one.\n\nLong bio paragraph two.",
    speaker_bio: "Speaker bio.",
  },
  "/journey": [],
  "/projects": [],
  "/talks": [],
  "/community": {
    name: "Velletri.dev",
    role: "Founder & Community Lead",
    mission: "Mission",
    description: "Description",
    vision: "Vision",
    collaboration: "Collaboration",
    founded_year: 2023,
    website_url: null,
    activities: [],
  },
  "/education": [],
  "/experiences": [],
  "/skills": [],
  "/passions": [],
  "/events": [
    {
      slug: "gdg-almaty-2026",
      event_name: "Qazaq IT Community Conference",
      session_title: null,
      short_description: null,
      full_description: null,
      start_date: "2026-07-15",
      end_date: "2026-07-15",
      year: 2026,
      month: 7,
      city: "Almaty",
      country: "Kazakhstan",
      continent: "Central Asia",
      latitude: 43.2389,
      longitude: 76.8897,
      venue: null,
      format: "conference",
      language: "en",
      topics: ["Gemini"],
      event_url: null,
      slides_url: null,
      recording_url: null,
      image: null,
      status: "completed",
      sessions_count: 1,
      is_featured: true,
      is_international_milestone: true,
      talk_title: null,
    },
    {
      slug: "m365-toronto-2026",
      event_name: "M365 Toronto",
      session_title: null,
      short_description: null,
      full_description: null,
      start_date: null,
      end_date: null,
      year: 2026,
      month: 9,
      city: "Toronto",
      country: "Canada",
      continent: "North America",
      latitude: 43.6532,
      longitude: -79.3832,
      venue: null,
      format: "conference",
      language: "en",
      topics: ["Microsoft 365"],
      event_url: null,
      slides_url: null,
      recording_url: null,
      image: null,
      status: "incoming",
      sessions_count: 1,
      is_featured: false,
      is_international_milestone: false,
      talk_title: null,
    },
  ],
  "/events/facets": {
    years: [2026],
    countries: ["Kazakhstan", "Canada"],
    continents: ["Central Asia", "North America"],
    topics: ["Gemini", "Microsoft 365"],
    event_names: ["Qazaq IT Community Conference", "M365 Toronto"],
    formats: ["conference"],
  },
  "/events/stats": {
    total_events: 32,
    total_countries: 10,
    total_cities: 26,
    total_continents: 3,
    first_year: 2023,
    last_year: 2026,
    international_count: 14,
    upcoming_count: 5,
    gdg_devfest_count: 13,
  },
  "/events/geojson": { type: "FeatureCollection", features: [] },
};

export function installFetchMock() {
  globalThis.fetch = vi.fn(async (input: RequestInfo | URL) => {
    const url = typeof input === "string" ? input : input.toString();
    const path = url.replace(window.location.origin, "").split("?")[0].replace("/api/v1", "");
    if (path in FIXTURES) return mockJsonResponse(FIXTURES[path]);
    return mockJsonResponse({ error: { code: "not_found", message: "Not found" } }, 404);
  }) as unknown as typeof fetch;
}
